=== PhillipTommerholt/tools/Godfather style/IP.AVID.RA.18005.rep0.seg0/representations/AVID.SA.18005.rep0/data/content/schema0/table13/table13.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.admin.ch/xmlns/siard/1.0/schema0/table13.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.admin.ch/xmlns/siard/1.0/schema0/table13.xsd">
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="row" type="rowType">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element name="c1" type="xs:integer"/>
      <xs:element name="c2" type="xs:integer"/>
      <xs:element name="c3" type="xs:decimal"/>
      <xs:element name="c4" type="xs:integer"/>
      <xs:element name="c5" type="xs:float"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== PhillipTommerholt/tools/Godfather style/IP.AVID.RA.18005.rep0.seg0/representations/AVID.SA.18005.rep0/data/content/schema0/table13/table13.xml
<?xml version="1.0" encoding="utf-8"?>
<table
  xmlns="http://www.admin.ch/xmlns/siard/1.0/schema0/table13.xsd"
  xsi:schemaLocation="http://www.admin.ch/xmlns/siard/1.0/schema0/table13.xsd table13.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <row><c1>10248</c1><c2>11</c2><c3>14.0000</c3><c4>12</c4><c5>0.0</c5></row>
  <row><c1>10248</c1><c2>42</c2><c3>9.8000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10248</c1><c2>72</c2><c3>34.8000</c3><c4>5</c4><c5>0.0</c5></row>
  <row><c1>10249</c1><c2>14</c2><c3>18.6000</c3><c4>9</c4><c5>0.0</c5></row>
  <row><c1>10249</c1><c2>51</c2><c3>42.4000</c3><c4>40</c4><c5>0.0</c5></row>
  <row><c1>10250</c1><c2>41</c2><c3>7.7000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10250</c1><c2>51</c2><c3>42.4000</c3><c4>35</c4><c5>0.15</c5></row>
  <row><c1>10250</c1><c2>65</c2><c3>16.8000</c3><c4>15</c4><c5>0.15</c5></row>
  <row><c1>10251</c1><c2>22</c2><c3>16.8000</c3><c4>6</c4><c5>0.05</c5></row>
  <row><c1>10251</c1><c2>57</c2><c3>15.6000</c3><c4>15</c4><c5>0.05</c5></row>
  <row><c1>10251</c1><c2>65</c2><c3>16.8000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10252</c1><c2>20</c2><c3>64.8000</c3><c4>40</c4><c5>0.05</c5></row>
  <row><c1>10252</c1><c2>33</c2><c3>2.0000</c3><c4>25</c4><c5>0.05</c5></row>
  <row><c1>10252</c1><c2>60</c2><c3>27.2000</c3><c4>40</c4><c5>0.0</c5></row>
  <row><c1>10253</c1><c2>31</c2><c3>10.0000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10253</c1><c2>39</c2><c3>14.4000</c3><c4>42</c4><c5>0.0</c5></row>
  <row><c1>10253</c1><c2>49</c2><c3>16.0000</c3><c4>40</c4><c5>0.0</c5></row>
  <row><c1>10254</c1><c2>24</c2><c3>3.6000</c3><c4>15</c4><c5>0.15</c5></row>
  <row><c1>10254</c1><c2>55</c2><c3>19.2000</c3><c4>21</c4><c5>0.15</c5></row>
  <row><c1>10254</c1><c2>74</c2><c3>8.0000</c3><c4>21</c4><c5>0.0</c5></row>
  <row><c1>10255</c1><c2>2</c2><c3>15.2000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10255</c1><c2>16</c2><c3>13.9000</c3><c4>35</c4><c5>0.0</c5></row>
  <row><c1>10255</c1><c2>36</c2><c3>15.2000</c3><c4>25</c4><c5>0.0</c5></row>
  <row><c1>10255</c1><c2>59</c2><c3>44.0000</c3><c4>30</c4><c5>0.0</c5></row>
  <row><c1>10256</c1><c2>53</c2><c3>26.2000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10256</c1><c2>77</c2><c3>10.4000</c3><c4>12</c4><c5>0.0</c5></row>
  <row><c1>10257</c1><c2>27</c2><c3>35.1000</c3><c4>25</c4><c5>0.0</c5></row>
  <row><c1>10257</c1><c2>39</c2><c3>14.4000</c3><c4>6</c4><c5>0.0</c5></row>
  <row><c1>10257</c1><c2>77</c2><c3>10.4000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10258</c1><c2>2</c2><c3>15.2000</c3><c4>50</c4><c5>0.2</c5></row>
  <row><c1>10258</c1><c2>5</c2><c3>17.0000</c3><c4>65</c4><c5>0.2</c5></row>
  <row><c1>10258</c1><c2>32</c2><c3>25.6000</c3><c4>6</c4><c5>0.2</c5></row>
  <row><c1>10259</c1><c2>21</c2><c3>8.0000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10259</c1><c2>37</c2><c3>20.8000</c3><c4>1</c4><c5>0.0</c5></row>
  <row><c1>10260</c1><c2>41</c2><c3>7.7000</c3><c4>16</c4><c5>0.25</c5></row>
  <row><c1>10260</c1><c2>57</c2><c3>15.6000</c3><c4>50</c4><c5>0.0</c5></row>
  <row><c1>10260</c1><c2>62</c2><c3>39.4000</c3><c4>15</c4><c5>0.25</c5></row>
  <row><c1>10260</c1><c2>70</c2><c3>12.0000</c3><c4>21</c4><c5>0.25</c5></row>
  <row><c1>10261</c1><c2>21</c2><c3>8.0000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10261</c1><c2>35</c2><c3>14.4000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10262</c1><c2>5</c2><c3>17.0000</c3><c4>12</c4><c5>0.2</c5></row>
  <row><c1>10262</c1><c2>7</c2><c3>24.0000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10262</c1><c2>56</c2><c3>30.4000</c3><c4>2</c4><c5>0.0</c5></row>
  <row><c1>10263</c1><c2>16</c2><c3>13.9000</c3><c4>60</c4><c5>0.25</c5></row>
  <row><c1>10263</c1><c2>24</c2><c3>3.6000</c3><c4>28</c4><c5>0.0</c5></row>
  <row><c1>10263</c1><c2>30</c2><c3>20.7000</c3><c4>60</c4><c5>0.25</c5></row>
  <row><c1>10263</c1><c2>74</c2><c3>8.0000</c3><c4>36</c4><c5>0.25</c5></row>
  <row><c1>10264</c1><c2>2</c2><c3>15.2000</c3><c4>35</c4><c5>0.0</c5></row>
  <row><c1>10264</c1><c2>41</c2><c3>7.7000</c3><c4>25</c4><c5>0.15</c5></row>
  <row><c1>10265</c1><c2>17</c2><c3>31.2000</c3><c4>30</c4><c5>0.0</c5></row>
  <row><c1>10265</c1><c2>70</c2><c3>12.0000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10266</c1><c2>12</c2><c3>30.4000</c3><c4>12</c4><c5>0.05</c5></row>
  <row><c1>10267</c1><c2>40</c2><c3>14.7000</c3><c4>50</c4><c5>0.0</c5></row>
  <row><c1>10267</c1><c2>59</c2><c3>44.0000</c3><c4>70</c4><c5>0.15</c5></row>
  <row><c1>10267</c1><c2>76</c2><c3>14.4000</c3><c4>15</c4><c5>0.15</c5></row>
  <row><c1>10268</c1><c2>29</c2><c3>99.0000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10268</c1><c2>72</c2><c3>27.8000</c3><c4>4</c4><c5>0.0</c5></row>
  <row><c1>10269</c1><c2>33</c2><c3>2.0000</c3><c4>60</c4><c5>0.05</c5></row>
  <row><c1>10269</c1><c2>72</c2><c3>27.8000</c3><c4>20</c4><c5>0.05</c5></row>
  <row><c1>10270</c1><c2>36</c2><c3>15.2000</c3><c4>30</c4><c5>0.0</c5></row>
  <row><c1>10270</c1><c2>43</c2><c3>36.8000</c3><c4>25</c4><c5>0.0</c5></row>
  <row><c1>10271</c1><c2>33</c2><c3>2.0000</c3><c4>24</c4><c5>0.0</c5></row>
  <row><c1>10272</c1><c2>20</c2><c3>64.8000</c3><c4>6</c4><c5>0.0</c5></row>
  <row><c1>10272</c1><c2>31</c2><c3>10.0000</c3><c4>40</c4><c5>0.0</c5></row>
  <row><c1>10272</c1><c2>72</c2><c3>27.8000</c3><c4>24</c4><c5>0.0</c5></row>
  <row><c1>10273</c1><c2>10</c2><c3>24.8000</c3><c4>24</c4><c5>0.05</c5></row>
  <row><c1>10273</c1><c2>31</c2><c3>10.0000</c3><c4>15</c4><c5>0.05</c5></row>
  <row><c1>10273</c1><c2>33</c2><c3>2.0000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10273</c1><c2>40</c2><c3>14.7000</c3><c4>60</c4><c5>0.05</c5></row>
  <row><c1>10273</c1><c2>76</c2><c3>14.4000</c3><c4>33</c4><c5>0.05</c5></row>
  <row><c1>10274</c1><c2>71</c2><c3>17.2000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10274</c1><c2>72</c2><c3>27.8000</c3><c4>7</c4><c5>0.0</c5></row>
  <row><c1>10275</c1><c2>24</c2><c3>3.6000</c3><c4>12</c4><c5>0.05</c5></row>
  <row><c1>10275</c1><c2>59</c2><c3>44.0000</c3><c4>6</c4><c5>0.05</c5></row>
  <row><c1>10276</c1><c2>10</c2><c3>24.8000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10276</c1><c2>13</c2><c3>4.8000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10277</c1><c2>28</c2><c3>36.4000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10277</c1><c2>62</c2><c3>39.4000</c3><c4>12</c4><c5>0.0</c5></row>
  <row><c1>10278</c1><c2>44</c2><c3>15.5000</c3><c4>16</c4><c5>0.0</c5></row>
  <row><c1>10278</c1><c2>59</c2><c3>44.0000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10278</c1><c2>63</c2><c3>35.1000</c3><c4>8</c4><c5>0.0</c5></row>
  <row><c1>10278</c1><c2>73</c2><c3>12.0000</c3><c4>25</c4><c5>0.0</c5></row>
  <row><c1>10279</c1><c2>17</c2><c3>31.2000</c3><c4>15</c4><c5>0.25</c5></row>
  <row><c1>10280</c1><c2>24</c2><c3>3.6000</c3><c4>12</c4><c5>0.0</c5></row>
  <row><c1>10280</c1><c2>55</c2><c3>19.2000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10280</c1><c2>75</c2><c3>6.2000</c3><c4>30</c4><c5>0.0</c5></row>
  <row><c1>10281</c1><c2>19</c2><c3>7.3000</c3><c4>1</c4><c5>0.0</c5></row>
  <row><c1>10281</c1><c2>24</c2><c3>3.6000</c3><c4>6</c4><c5>0.0</c5></row>
  <row><c1>10281</c1><c2>35</c2><c3>14.4000</c3><c4>4</c4><c5>0.0</c5></row>
  <row><c1>10282</c1><c2>30</c2><c3>20.7000</c3><c4>6</c4><c5>0.0</c5></row>
  <row><c1>10282</c1><c2>57</c2><c3>15.6000</c3><c4>2</c4><c5>0.0</c5></row>
  <row><c1>10283</c1><c2>15</c2><c3>12.4000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10283</c1><c2>19</c2><c3>7.3000</c3><c4>18</c4><c5>0.0</c5></row>
  <row><c1>10283</c1><c2>60</c2><c3>27.2000</c3><c4>35</c4><c5>0.0</c5></row>
  <row><c1>10283</c1><c2>72</c2><c3>27.8000</c3><c4>3</c4><c5>0.0</c5></row>
  <row><c1>10284</c1><c2>27</c2><c3>35.1000</c3><c4>15</c4><c5>0.25</c5></row>
  <row><c1>10284</c1><c2>44</c2><c3>15.5000</c3><c4>21</c4><c5>0.0</c5></row>
  <row><c1>10284</c1><c2>60</c2><c3>27.2000</c3><c4>20</c4><c5>0.25</c5></row>
  <row><c1>10284</c1><c2>67</c2><c3>11.2000</c3><c4>5</c4><c5>0.25</c5></row>
  <row><c1>10285</c1><c2>1</c2><c3>14.4000</c3><c4>45</c4><c5>0.2</c5></row>
  <row><c1>10285</c1><c2>40</c2><c3>14.7000</c3><c4>40</c4><c5>0.2</c5></row>
  <row><c1>10285</c1><c2>53</c2><c3>26.2000</c3><c4>36</c4><c5>0.2</c5></row>
  <row><c1>10286</c1><c2>35</c2><c3>14.4000</c3><c4>100</c4><c5>0.0</c5></row>
  <row><c1>10286</c1><c2>62</c2><c3>39.4000</c3><c4>40</c4><c5>0.0</c5></row>
  <row><c1>10287</c1><c2>16</c2><c3>13.9000</c3><c4>40</c4><c5>0.15</c5></row>
  <row><c1>10287</c1><c2>34</c2><c3>11.2000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10287</c1><c2>46</c2><c3>9.6000</c3><c4>15</c4><c5>0.15</c5></row>
  <row><c1>10288</c1><c2>54</c2><c3>5.9000</c3><c4>10</c4><c5>0.1</c5></row>
  <row><c1>10288</c1><c2>68</c2><c3>10.0000</c3><c4>3</c4><c5>0.1</c5></row>
  <row><c1>10289</c1><c2>3</c2><c3>8.0000</c3><c4>30</c4><c5>0.0</c5></row>
  <row><c1>10289</c1><c2>64</c2><c3>26.6000</c3><c4>9</c4><c5>0.0</c5></row>
  <row><c1>10290</c1><c2>5</c2><c3>17.0000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10290</c1><c2>29</c2><c3>99.0000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10290</c1><c2>49</c2><c3>16.0000</c3><c4>15</c4><c5>0.0</c5></row>
  <row><c1>10290</c1><c2>77</c2><c3>10.4000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10291</c1><c2>13</c2><c3>4.8000</c3><c4>20</c4><c5>0.1</c5></row>
  <row><c1>10291</c1><c2>44</c2><c3>15.5000</c3><c4>24</c4><c5>0.1</c5></row>
  <row><c1>10291</c1><c2>51</c2><c3>42.4000</c3><c4>2</c4><c5>0.1</c5></row>
  <row><c1>10292</c1><c2>20</c2><c3>64.8000</c3><c4>20</c4><c5>0.0</c5></row>
  <row><c1>10293</c1><c2>18</c2><c3>50.0000</c3><c4>12</c4><c5>0.0</c5></row>
  <row><c1>10293</c1><c2>24</c2><c3>3.6000</c3><c4>10</c4><c5>0.0</c5></row>
  <row><c1>10293</c1><c2>63</c2><c3>35.1000</c3><c4>5</c4><c5>0.0</c5></row>
  <row><c1>10293</c1><c2>75</c2><c3>6.2000</c3><c4>6</c4><c5>0.0</c5></row>
